# Unity states
UNITY_DOWN = 0
UNITY_UP = 1
UNITY_READY = 2
UNITY_FINISHED = 3

# TCP server states
SERVER_DOWN = 0
SERVER_UP = 1

# MEDUSA MODES
TRAIN_MODE = "Train"
ONLINE_MODE = "Online"
FAST_MODE = "Fast"

# FUNCTIONALITIES
FUNC_NONE = 'NONE'
FUNC_PAUSE = 'PAUSE'
FUNC_GOTO = 'GOTO'
FUNC_BS = 'BS'
FUNC_END = 'END'